In [3]:
# Features selected for the MVP
features = [
    'HighBP',
    'HighChol',
    'BMI',
    'Smoker',
    'PhysActivity',
    'GenHlth',
    'Age',
    'Sex'
]

# Target
target = 'Diabetes_012'

# Create dataset containing only selected features + target
model_df = df[features + [target]].copy()

print("Modeling dataset shape:", model_df.shape)
print("\nSelected columns:")
print(model_df.columns.tolist())

display(model_df.head())

Modeling dataset shape: (253680, 9)

Selected columns:
['HighBP', 'HighChol', 'BMI', 'Smoker', 'PhysActivity', 'GenHlth', 'Age', 'Sex', 'Diabetes_012']


,HighBP,HighChol,BMI,Smoker,PhysActivity,GenHlth,Age,Sex,Diabetes_012
0,1.0,1.0,40.0,1.0,0.0,5.0,9.0,0.0,0.0
1,0.0,0.0,25.0,1.0,1.0,3.0,7.0,0.0,0.0
2,1.0,1.0,28.0,0.0,0.0,5.0,9.0,0.0,0.0
3,1.0,0.0,27.0,0.0,1.0,2.0,11.0,0.0,0.0
4,1.0,1.0,24.0,0.0,1.0,2.0,11.0,0.0,0.0


In [4]:
# Check data types
print("DATA TYPES:")
print(model_df.dtypes)

# Check missing values
print("\nMISSING VALUES:")
print(model_df.isnull().sum())

# Check duplicate rows
print("\nDUPLICATE ROWS:")
print(model_df.duplicated().sum())

# Check value ranges / unique values
print("\nUNIQUE VALUES:")
for column in model_df.columns:
    print(f"{column}: {sorted(model_df[column].unique())}")

DATA TYPES:
HighBP          float64
HighChol        float64
BMI             float64
Smoker          float64
PhysActivity    float64
GenHlth         float64
Age             float64
Sex             float64
Diabetes_012    float64
dtype: object

MISSING VALUES:
HighBP          0
HighChol        0
BMI             0
Smoker          0
PhysActivity    0
GenHlth         0
Age             0
Sex             0
Diabetes_012    0
dtype: int64

DUPLICATE ROWS:
197586

UNIQUE VALUES:
HighBP: [np.float64(0.0), np.float64(1.0)]
HighChol: [np.float64(0.0), np.float64(1.0)]
BMI: [np.float64(12.0), np.float64(13.0), np.float64(14.0), np.float64(15.0), np.float64(16.0), np.float64(17.0), np.float64(18.0), np.float64(19.0), np.float64(20.0), np.float64(21.0), np.float64(22.0), np.float64(23.0), np.float64(24.0), np.float64(25.0), np.float64(26.0), np.float64(27.0), np.float64(28.0), np.float64(29.0), np.float64(30.0), np.float64(31.0), np.float64(32.0), np.float64(33.0), np.float64(34.0), np.float64(35.0), 

In [5]:
# Check the number of duplicate rows
duplicate_count = model_df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 197586


In [6]:
# Check duplicates in the original full dataset
original_duplicate_count = df.duplicated().sum()

print("Duplicate rows in original dataset:", original_duplicate_count)

Duplicate rows in original dataset: 23899


In [7]:
print("Target distribution:")
print(model_df["Diabetes_012"].value_counts().sort_index())

print("\nTarget percentages:")
print(
    model_df["Diabetes_012"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

Target distribution:
Diabetes_012
0.0    213703
1.0      4631
2.0     35346
Name: count, dtype: int64

Target percentages:
Diabetes_012
0.0    84.24
1.0     1.83
2.0    13.93
Name: proportion, dtype: float64


In [8]:
from sklearn.model_selection import train_test_split

X = model_df.drop(columns=['Diabetes_012'])
y = model_df['Diabetes_012']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (202944, 8)
Test shape: (50736, 8)


In [2]:
import pandas as pd

# Load the original chronic health dataset
df = pd.read_csv('../data/raw/diabetes_012_health_indicators_BRFSS2015.csv')

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (253680, 22)

Columns:
['Diabetes_012', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth', 'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education', 'Income']


In [9]:
from sklearn.ensemble import RandomForestClassifier

# Create the Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

# Train the model
rf_model.fit(X_train, y_train)

print("Random Forest model trained successfully!")

Random Forest model trained successfully!


In [10]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Make predictions on the test set
y_pred = rf_model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", round(accuracy * 100, 2), "%")

# Detailed classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Test Accuracy: 83.01 %

Classification Report:
              precision    recall  f1-score   support

         0.0       0.87      0.95      0.91     42741
         1.0       0.04      0.01      0.01       926
         2.0       0.41      0.22      0.29      7069

    accuracy                           0.83     50736
   macro avg       0.44      0.39      0.40     50736
weighted avg       0.79      0.83      0.80     50736


Confusion Matrix:
[[40549    87  2105]
 [  797     5   124]
 [ 5461    48  1560]]


In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Test Accuracy:", round(accuracy_score(y_test, y_pred) * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Test Accuracy: 71.57 %

Classification Report:
              precision    recall  f1-score   support

         0.0       0.92      0.73      0.81     42741
         1.0       0.31      0.65      0.42      7995

    accuracy                           0.72     50736
   macro avg       0.61      0.69      0.62     50736
weighted avg       0.82      0.72      0.75     50736


Confusion Matrix:
[[31086 11655]
 [ 2771  5224]]


In [11]:
y_binary = y.replace({0: 0, 1: 1, 2: 1})  # 0 = no diabetes, 1 = at risk

X_train, X_test, y_train, y_test = train_test_split(
    X, y_binary, test_size=0.2, stratify=y_binary, random_state=42
)

model = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Test Accuracy:", round(accuracy_score(y_test, y_pred) * 100, 2), "%")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Test Accuracy: 71.57 %
              precision    recall  f1-score   support

         0.0       0.92      0.73      0.81     42741
         1.0       0.31      0.65      0.42      7995

    accuracy                           0.72     50736
   macro avg       0.61      0.69      0.62     50736
weighted avg       0.82      0.72      0.75     50736

[[31086 11655]
 [ 2771  5224]]


In [13]:
import joblib
import os

os.makedirs('../models', exist_ok=True)

joblib.dump(model, '../models/chronic_model.pkl')
joblib.dump(list(X_train.columns), '../models/chronic_features.pkl')

print("Saved. Feature order:", list(X_train.columns))

Saved. Feature order: ['HighBP', 'HighChol', 'BMI', 'Smoker', 'PhysActivity', 'GenHlth', 'Age', 'Sex']


# Chronic Health Preprocessing and Model Training

Preprocessing and training of the Random Forest model for chronic health risk prediction using selected features from the CDC Diabetes Health Indicators dataset.